<a href="https://colab.research.google.com/github/mtsilimos/NLP-projects/blob/main/3_Keras_for_researchers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import tensorflow as tf
import keras

In [2]:
#create constant tensors is via tf.ones and tf.zeros

print(tf.ones(shape=(2, 1)))
print(tf.zeros(shape=(2, 1)))

tf.Tensor(
[[1.]
 [1.]], shape=(2, 1), dtype=float32)
tf.Tensor(
[[0.]
 [0.]], shape=(2, 1), dtype=float32)


In [8]:
#create random constant tensors
x1 = tf.random.normal(shape=(2, 2), mean=0.0, stddev=1.0)

x2 = tf.random.uniform(shape=(2, 2), minval=0, maxval=10, dtype="int32")




In [9]:
x1

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.86942405,  0.23034714],
       [ 2.5269372 ,  0.7496723 ]], dtype=float32)>

In [7]:
x2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 9],
       [0, 0]], dtype=int32)>